from uuid import UUID
from enum import Enum

class NewInstitution:
    def __new__(cls, id: UUID, name: str): ...

class UserRole(Enum):
    AppAdmin = ...
    BiologyStaff = ...
    ComputationalStaff = ...

class NewPerson:
    def __new__(
        cls, name: str, email: str, institution_id: UUID, roles: list[UserRole]
    ): ...
