services:
  scamplers-api:
    image: ghcr.io/demhadais/scamplers-api
  scamplers-ui:
    image: ghcr.io/demhadais/scamplers-ui
  caddy:
    environment:
      TLS_SETTINGS: /run/secrets/tls_certificate /run/secrets/tls_key
    secrets:
      - tls_certificate
      - tls_key
secrets:
  tls_certificate:
    file: ${SCAMPLERS_TLS_CERTIFICATE_PATH}
  tls_key:
    file: ${SCAMPLERS_TLS_KEY_PATH}
