/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstitutionQuery {
  ids?: string[];
  limit?: number;
  name?: string | null;
  offset?: number;
  order_by?: {
    descending?: boolean;
    field?: "id" | "name";
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
