/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PersonQuery {
  email?: string | null;
  ids?: string[];
  limit?: number;
  microsoft_entra_oids?: string[];
  name?: string | null;
  offset?: number;
  orcid?: string | null;
  order_by?: {
    descending?: boolean;
    field?: "id" | "email" | "name";
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
