/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PersonSummary {
  email?: string | null;
  email_verified: boolean;
  id: string;
  institution_id: string;
  links: {
    [k: string]: string;
  };
  microsoft_entra_oid?: string | null;
  name: string;
  orcid?: string | null;
  [k: string]: unknown;
}
