/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Person {
  email?: string | null;
  email_verified: boolean;
  id: string;
  institution: {
    id: string;
    links: {
      [k: string]: string;
    };
    name: string;
    [k: string]: unknown;
  };
  institution_id: string;
  links: {
    [k: string]: string;
  };
  microsoft_entra_oid?: string | null;
  name: string;
  orcid?: string | null;
  roles: ("app_admin" | "biology_staff" | "computational_staff")[];
  [k: string]: unknown;
}
