#!/usr/bin/env bash

set -euo pipefail

cd rust

# Exclude scamplers-schema since that's generated by diesel and we don't want clippy to touch that
cargo clippy --fix --workspace --allow-dirty --exclude scamplers-schema --all-features

# Run clippy again for wasm32-unknown-unknown, excluding scamplepy as well since that will fail to compile
cargo clippy --fix --workspace --allow-dirty --exclude scamplers-schema --exclude scamplepy --target wasm32-unknown-unknown
cargo +nightly fmt
