/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreatedUser {
  api_key: string;
  email?: string | null;
  id: string;
  institution_id: string;
  links: Links;
  ms_user_id?: string | null;
  name: string;
  orcid?: string | null;
  [k: string]: unknown;
}
export interface Links {
  [k: string]: string;
}
