/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OrdinalColumns = "Id" | "Email" | "Name";

export interface PersonQuery {
  emails?: string[];
  ids?: string[];
  limit?: number;
  ms_user_ids?: string[];
  names?: string[];
  offset?: number;
  orcids?: string[];
  order_by?: {
    descending?: boolean;
    field?: OrdinalColumns;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
