name: Check SQL Code

on:
  pull_request:
    paths:
      - db/**
    branches:
      - main

jobs:
  lint_sql:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install sqlfluff
        run: pip install sqlfluff

      - name: Lint code
        working-directory: db
        run: sqlfluff lint .
